-- MySQL Script generated by MySQL Workbench
-- Sat Jul 16 23:51:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET utf8 ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`character` (
  `id_character` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `history` VARCHAR(225) NOT NULL,
  `Associated-movies-or-series` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_character`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`associated-movies-or-series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`associated-movies-or-series` (
  `id_associated-movies-or-series` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `Creation-date` DATE NOT NULL,
  `Qualification` INT NOT NULL,
  `associated-characters` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_associated-movies-or-series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `associated-movies-or-series` VARCHAR(255) NOT NULL,
  `id_character` INT NOT NULL,
  `id_associated-movies-or-series` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_character`
    FOREIGN KEY (`id`)
    REFERENCES `bd`.`character` (`id_character`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_associated-movies-or-series`
    FOREIGN KEY (`id`)
    REFERENCES `bd`.`associated-movies-or-series` (`id_associated-movies-or-series`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
